/** @format */

// Example: You can expand this list or use a full dataset
export const airports = [
	{ code: 'BNE', name: 'Brisbane Airport', city: 'Brisbane' },
	{ code: 'PER', name: 'Perth Airport', city: 'Perth' },
	{ code: 'ADL', name: 'Adelaide Airport', city: 'Adelaide' },
	{ code: 'AKL', name: 'Auckland Airport', city: 'Auckland' },
	{ code: 'WLG', name: 'Wellington International Airport', city: 'Wellington' },
	{ code: 'CHC', name: 'Christchurch International Airport', city: 'Christchurch' },
	{ code: 'DOH', name: 'Hamad International Airport', city: 'Doha' },
	{ code: 'RUH', name: 'King Khalid International Airport', city: 'Riyadh' },
	{ code: 'JED', name: 'King Abdulaziz International Airport', city: 'Jeddah' },
	{ code: 'CAI', name: 'Cairo International Airport', city: 'Cairo' },
	{ code: 'CMN', name: 'Mohammed V International Airport', city: 'Casablanca' },
	{ code: 'RAK', name: 'Marrakesh Menara Airport', city: 'Marrakesh' },
	{ code: 'NBO', name: 'Jomo Kenyatta International Airport', city: 'Nairobi' },
	{ code: 'LOS', name: 'Murtala Muhammed International Airport', city: 'Lagos' },
	{ code: 'ACC', name: 'Kotoka International Airport', city: 'Accra' },
	{ code: 'DAR', name: 'Julius Nyerere International Airport', city: 'Dar es Salaam' },
	{ code: 'CPT', name: 'Cape Town International Airport', city: 'Cape Town' },
	{ code: 'LAD', name: 'Quatro de Fevereiro Airport', city: 'Luanda' },
	{ code: 'ABV', name: 'Nnamdi Azikiwe International Airport', city: 'Abuja' },
	{ code: 'KRT', name: 'Khartoum International Airport', city: 'Khartoum' },
	{ code: 'ADD', name: 'Addis Ababa Bole International Airport', city: 'Addis Ababa' },
	{ code: 'JNB', name: 'O. R. Tambo International Airport', city: 'Johannesburg' },
	{ code: 'DUR', name: 'King Shaka International Airport', city: 'Durban' },
	{ code: 'LHE', name: 'Allama Iqbal International Airport', city: 'Lahore' },
	{ code: 'ISB', name: 'Islamabad International Airport', city: 'Islamabad' },
	{ code: 'KHI', name: 'Jinnah International Airport', city: 'Karachi' },
	{ code: 'DAC', name: 'Hazrat Shahjalal International Airport', city: 'Dhaka' },
	{ code: 'CGK', name: 'Soekarno–Hatta International Airport', city: 'Jakarta' },
	{ code: 'MNL', name: 'Ninoy Aquino International Airport', city: 'Manila' },
	{ code: 'SGN', name: 'Tan Son Nhat International Airport', city: 'Ho Chi Minh City' },
	{ code: 'HAN', name: 'Noi Bai International Airport', city: 'Hanoi' },
	{ code: 'KIX', name: 'Kansai International Airport', city: 'Osaka' },
	{ code: 'NGO', name: 'Chubu Centrair International Airport', city: 'Nagoya' },
	{ code: 'CTS', name: 'New Chitose Airport', city: 'Sapporo' },
	{ code: 'FUK', name: 'Fukuoka Airport', city: 'Fukuoka' },
	{ code: 'PEK', name: 'Beijing Capital International Airport', city: 'Beijing' },
	{ code: 'PVG', name: 'Shanghai Pudong International Airport', city: 'Shanghai' },
	{ code: 'CAN', name: 'Guangzhou Baiyun International Airport', city: 'Guangzhou' },
	{ code: 'SZX', name: 'Shenzhen Bao’an International Airport', city: 'Shenzhen' },
	{ code: 'JFK', name: 'John F. Kennedy International Airport', city: 'New York' },
	{ code: 'LHR', name: 'London Heathrow Airport', city: 'London' },
	{ code: 'LAX', name: 'Los Angeles International Airport', city: 'Los Angeles' },
	{ code: 'DXB', name: 'Dubai International Airport', city: 'Dubai' },
	{ code: 'CDG', name: 'Charles de Gaulle Airport', city: 'Paris' },
	{ code: 'HND', name: 'Tokyo Haneda Airport', city: 'Tokyo' },
	{ code: 'SIN', name: 'Singapore Changi Airport', city: 'Singapore' },
	{ code: 'SYD', name: 'Sydney Kingsford Smith Airport', city: 'Sydney' },
	{ code: 'FRA', name: 'Frankfurt Airport', city: 'Frankfurt' },
	{ code: 'IST', name: 'Istanbul Airport', city: 'Istanbul' },
	{ code: 'AMS', name: 'Amsterdam Schiphol Airport', city: 'Amsterdam' },
	{ code: 'MAD', name: 'Adolfo Suárez Madrid–Barajas Airport', city: 'Madrid' },
	{ code: 'BCN', name: 'Barcelona El Prat Airport', city: 'Barcelona' },
	{ code: 'MUC', name: 'Munich Airport', city: 'Munich' },
	{ code: 'YYZ', name: 'Toronto Pearson International Airport', city: 'Toronto' },
	{ code: 'GRU', name: 'São Paulo–Guarulhos International Airport', city: 'São Paulo' },
	{ code: 'JNB', name: 'O. R. Tambo International Airport', city: 'Johannesburg' },
	{ code: 'SVO', name: 'Sheremetyevo International Airport', city: 'Moscow' },
	{ code: 'ICN', name: 'Incheon International Airport', city: 'Seoul' },
	{ code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport', city: 'Mumbai' },
	{ code: 'DEL', name: 'Indira Gandhi International Airport', city: 'Delhi' },
	{ code: 'MEX', name: 'Mexico City International Airport', city: 'Mexico City' },
	{ code: 'SFO', name: 'San Francisco International Airport', city: 'San Francisco' },
	{ code: 'SEA', name: 'Seattle-Tacoma International Airport', city: 'Seattle' },
	{ code: 'ORD', name: 'Chicago O’Hare International Airport', city: 'Chicago' },
	{ code: 'ATL', name: 'Hartsfield–Jackson Atlanta International Airport', city: 'Atlanta' },
	{ code: 'MIA', name: 'Miami International Airport', city: 'Miami' },
	{ code: 'EWR', name: 'Newark Liberty International Airport', city: 'Newark' },
	{ code: 'DFW', name: 'Dallas/Fort Worth International Airport', city: 'Dallas' },
	{ code: 'DEN', name: 'Denver International Airport', city: 'Denver' },
	{ code: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok' },
	{ code: 'KUL', name: 'Kuala Lumpur International Airport', city: 'Kuala Lumpur' },
	{ code: 'HKG', name: 'Hong Kong International Airport', city: 'Hong Kong' },
	{ code: 'GIG', name: 'Rio de Janeiro–Galeão International Airport', city: 'Rio de Janeiro' },
	{ code: 'LIM', name: 'Jorge Chávez International Airport', city: 'Lima' },
	{ code: 'CPT', name: 'Cape Town International Airport', city: 'Cape Town' },
	{ code: 'DME', name: 'Domodedovo International Airport', city: 'Moscow' },
	{ code: 'ZRH', name: 'Zurich Airport', city: 'Zurich' },
	{ code: 'VIE', name: 'Vienna International Airport', city: 'Vienna' },
	{ code: 'OSL', name: 'Oslo Gardermoen Airport', city: 'Oslo' },
	{ code: 'ARN', name: 'Stockholm Arlanda Airport', city: 'Stockholm' },
	{ code: 'HEL', name: 'Helsinki Airport', city: 'Helsinki' },
];
